name: CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create Android signing files
        run: |
          echo "${{ secrets.KEYPROPERTIES }}" | base64 --decode > android/key.properties
          echo "${{ secrets.KEYJKS }}" | base64 --decode > android/app/key.jks

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android app
        run: flutter build apk

      - name: Move download files to files
        run: |
          mkdir files
          mv build/app/outputs/flutter-apk/app-release.apk files/android-app.apk

      - name: Upload files
        uses: actions/upload-artifact@v2
        with: 
          name: files
          path: files
